// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: leaderboard.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_leaderboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{0}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RegionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      string                 `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	SeasonId      string                 `protobuf:"bytes,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	IsFinal       bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	UserCount     int32                  `protobuf:"varint,5,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	TopK          *TopKSummary           `protobuf:"bytes,6,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Histogram     *HistogramSummary      `protobuf:"bytes,7,opt,name=histogram,proto3" json:"histogram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionSummary) Reset() {
	*x = RegionSummary{}
	mi := &file_leaderboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionSummary) ProtoMessage() {}

func (x *RegionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionSummary.ProtoReflect.Descriptor instead.
func (*RegionSummary) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{1}
}

func (x *RegionSummary) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *RegionSummary) GetSeasonId() string {
	if x != nil {
		return x.SeasonId
	}
	return ""
}

func (x *RegionSummary) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RegionSummary) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *RegionSummary) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *RegionSummary) GetTopK() *TopKSummary {
	if x != nil {
		return x.TopK
	}
	return nil
}

func (x *RegionSummary) GetHistogram() *HistogramSummary {
	if x != nil {
		return x.Histogram
	}
	return nil
}

type TopKSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopKSummary) Reset() {
	*x = TopKSummary{}
	mi := &file_leaderboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopKSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopKSummary) ProtoMessage() {}

func (x *TopKSummary) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopKSummary.ProtoReflect.Descriptor instead.
func (*TopKSummary) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{2}
}

func (x *TopKSummary) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TopKSummary) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type HistogramSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Buckets       []*HistogramBucket     `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramSummary) Reset() {
	*x = HistogramSummary{}
	mi := &file_leaderboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramSummary) ProtoMessage() {}

func (x *HistogramSummary) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramSummary.ProtoReflect.Descriptor instead.
func (*HistogramSummary) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{3}
}

func (x *HistogramSummary) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *HistogramSummary) GetBuckets() []*HistogramBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type HistogramBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowerBound    int64                  `protobuf:"varint,1,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound    int64                  `protobuf:"varint,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramBucket) Reset() {
	*x = HistogramBucket{}
	mi := &file_leaderboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBucket) ProtoMessage() {}

func (x *HistogramBucket) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBucket.ProtoReflect.Descriptor instead.
func (*HistogramBucket) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{4}
}

func (x *HistogramBucket) GetLowerBound() int64 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *HistogramBucket) GetUpperBound() int64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *HistogramBucket) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int64                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_leaderboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_leaderboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_leaderboard_proto_rawDescGZIP(), []int{5}
}

func (x *Entry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Entry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_leaderboard_proto protoreflect.FileDescriptor

const file_leaderboard_proto_rawDesc = "" +
	"\n" +
	"\x11leaderboard.proto\x12\x17distributed_leaderboard\"+\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9d\x02\n" +
	"\rRegionSummary\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\tR\bregionId\x12\x1b\n" +
	"\tseason_id\x18\x02 \x01(\tR\bseasonId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\x12\x1d\n" +
	"\n" +
	"user_count\x18\x05 \x01(\x05R\tuserCount\x129\n" +
	"\x05top_k\x18\x06 \x01(\v2$.distributed_leaderboard.TopKSummaryR\x04topK\x12G\n" +
	"\thistogram\x18\a \x01(\v2).distributed_leaderboard.HistogramSummaryR\thistogram\"]\n" +
	"\vTopKSummary\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.distributed_leaderboard.EntryR\aentries\"l\n" +
	"\x10HistogramSummary\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12B\n" +
	"\abuckets\x18\x02 \x03(\v2(.distributed_leaderboard.HistogramBucketR\abuckets\"i\n" +
	"\x0fHistogramBucket\x12\x1f\n" +
	"\vlower_bound\x18\x01 \x01(\x03R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x02 \x01(\x03R\n" +
	"upperBound\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"6\n" +
	"\x05Entry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score2x\n" +
	"\x12ReplicationService\x12b\n" +
	"\x0ePublishSummary\x12&.distributed_leaderboard.RegionSummary\x1a(.distributed_leaderboard.PublishResponseB0Z.github.com/Rx-11/distributed-leaderboard/protob\x06proto3"

var (
	file_leaderboard_proto_rawDescOnce sync.Once
	file_leaderboard_proto_rawDescData []byte
)

func file_leaderboard_proto_rawDescGZIP() []byte {
	file_leaderboard_proto_rawDescOnce.Do(func() {
		file_leaderboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)))
	})
	return file_leaderboard_proto_rawDescData
}

var file_leaderboard_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_leaderboard_proto_goTypes = []any{
	(*PublishResponse)(nil),  // 0: distributed_leaderboard.PublishResponse
	(*RegionSummary)(nil),    // 1: distributed_leaderboard.RegionSummary
	(*TopKSummary)(nil),      // 2: distributed_leaderboard.TopKSummary
	(*HistogramSummary)(nil), // 3: distributed_leaderboard.HistogramSummary
	(*HistogramBucket)(nil),  // 4: distributed_leaderboard.HistogramBucket
	(*Entry)(nil),            // 5: distributed_leaderboard.Entry
}
var file_leaderboard_proto_depIdxs = []int32{
	2, // 0: distributed_leaderboard.RegionSummary.top_k:type_name -> distributed_leaderboard.TopKSummary
	3, // 1: distributed_leaderboard.RegionSummary.histogram:type_name -> distributed_leaderboard.HistogramSummary
	5, // 2: distributed_leaderboard.TopKSummary.entries:type_name -> distributed_leaderboard.Entry
	4, // 3: distributed_leaderboard.HistogramSummary.buckets:type_name -> distributed_leaderboard.HistogramBucket
	1, // 4: distributed_leaderboard.ReplicationService.PublishSummary:input_type -> distributed_leaderboard.RegionSummary
	0, // 5: distributed_leaderboard.ReplicationService.PublishSummary:output_type -> distributed_leaderboard.PublishResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_leaderboard_proto_init() }
func file_leaderboard_proto_init() {
	if File_leaderboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leaderboard_proto_rawDesc), len(file_leaderboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leaderboard_proto_goTypes,
		DependencyIndexes: file_leaderboard_proto_depIdxs,
		MessageInfos:      file_leaderboard_proto_msgTypes,
	}.Build()
	File_leaderboard_proto = out.File
	file_leaderboard_proto_goTypes = nil
	file_leaderboard_proto_depIdxs = nil
}
